services:
  - type: web
    name: attendance-crm-server
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          name: attendance-crm-client
          type: static_site
          envVarKey: RENDER_EXTERNAL_URL
      - key: MONGODB_URI
        sync: false
  - type: static_site
    name: attendance-crm-client
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: attendance-crm-client
          type: static_site
          envVarKey: RENDER_EXTERNAL_URL
